### PR TITLE
Switched from AsyncDuplicateLock to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Switched from AsyncDuplicateLock to AsyncKeyedLock, which provides better performance and lower memory usage.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@JacobAtchley

**Comment by MarkCiliaVincenti** [comment]
> Hello @MarkCiliaVincenti, Thanks for contributing to our project! Looks like you've had some version updates over the last few weeks. Let us know when you get a version locked down and we can look at merging this in.

Thanks, you're right with regards to the versions. I'm done for now though so there won't be any more updates in the short term.

**Comment by MarkCiliaVincenti** [comment]
@JacobAtchley nudge :)

**Comment by MarkCiliaVincenti** [comment]
@JacobAtchley

**Comment by MarkCiliaVincenti** [comment]
@JacobAtchley

**Comment by MarkCiliaVincenti** [comment]
@JacobAtchley any thoughts on this please?

**Comment by MarkCiliaVincenti** [comment]
> Hello @MarkCiliaVincenti, Thanks for contributing to our project! Looks like you've had some version updates over the last few weeks. Let us know when you get a version locked down and we can look at merging this in.

@JacobAtchley are you interested in this PR please, or shall I close it?

**Comment by JacobAtchley** [comment]
Hello @MarkCiliaVincenti, sorry for the late response, i've been out sick and with the holidays i fell behind on replying

do you have any metrics on memory saved when using your package? 
i would like to quantify the changes we are making

**Comment by MarkCiliaVincenti** [comment]
> Hello @MarkCiliaVincenti, sorry for the late response, i've been out sick and with the holidays i fell behind on replying
> 
> do you have any metrics on memory saved when using your package? i would like to quantify the changes we are making

Hi @JacobAtchley, hope you are feeling better. I am running benchmarks right now right on GitHub so you can be confident that there's no fabrication involved. They're running right now on https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/3941257523/jobs/6743429454 and I'm confident enough to give you this link whilst it's still processing with no idea what the exact result will be.

**Comment by JacobAtchley** [comment]
> d

sweet! i'll wait for the results and review them ASAP! thank you!

**Comment by MarkCiliaVincenti** [comment]
> sweet! i'll wait for the results and review them ASAP! thank you!

`|                         Method | NumberOfLocks | Contention | GuidReversals |              Mean |           Error |          StdDev |            Median | Ratio | RatioSD |        Gen0 |       Gen1 |      Gen2 |    Allocated | Alloc Ratio |
|------------------------------- |-------------- |----------- |-------------- |------------------:|----------------:|----------------:|------------------:|------:|--------:|------------:|-----------:|----------:|-------------:|------------:|
|                 AsyncKeyedLock |           200 |        100 |             0 |     18,374.673 us |   1,389.3955 us |   4,052.9319 us |     16,073.415 us |  1.00 |    0.00 |           - |          - |         - |    4365952 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |        100 |             0 |     14,930.484 us |     331.3341 us |     907.0216 us |     14,754.497 us |  0.83 |    0.15 |           - |          - |         - |    6766576 B |        1.55 |
| AsyncDuplicateLockFromAutoCrud |           200 |        100 |             0 |     12,493.586 us |     153.2985 us |     284.1487 us |     12,459.866 us |  0.63 |    0.15 |           - |          - |         - |    8365952 B |        1.92 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |           200 |        100 |             1 |     42,188.215 us |     831.9946 us |   1,366.9910 us |     41,748.055 us |  1.00 |    0.00 |           - |          - |         - |    7246232 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |        100 |             1 |     42,814.593 us |     768.2209 us |   1,825.7583 us |     42,286.862 us |  1.02 |    0.06 |           - |          - |         - |    9[6468](https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/3941257523/jobs/6743429454#step:4:6469)56 B |        1.33 |
| AsyncDuplicateLockFromAutoCrud |           200 |        100 |             1 |     38,510.127 us |     714.1923 us |   1,153.2875 us |     38,467.912 us |  0.91 |    0.04 |           - |          - |         - |   11246232 B |        1.55 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |           200 |        100 |             5 |    130,782.557 us |   2,571.5607 us |   4,366.7052 us |    128,930.256 us |  1.00 |    0.00 |           - |          - |         - |   18766232 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |        100 |             5 |    138,873.728 us |   2,745.1239 us |   2,433.4809 us |    137,878.658 us |  1.06 |    0.03 |   1000.0000 |          - |         - |   21167136 B |        1.13 |
| AsyncDuplicateLockFromAutoCrud |           200 |        100 |             5 |    140,483.374 us |   2,806.6619 us |   4,113.9687 us |    139,221.776 us |  1.07 |    0.04 |   1000.0000 |          - |         - |   22766512 B |        1.21 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |           200 |      10000 |             0 |  2,413,251.974 us |  47,209.0154 us |  44,159.3423 us |  2,418,256.987 us |  1.00 |    0.00 |  22000.0000 | 21000.0000 | 3000.0000 |  417571656 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |      10000 |             0 |  2,616,445.545 us |  50,626.8669 us |  67,585.4132 us |  2,614,127.952 us |  1.08 |    0.04 |  33000.0000 | 32000.0000 | 1000.0000 |  657564768 B |        1.57 |
| AsyncDuplicateLockFromAutoCrud |           200 |      10000 |             0 |  2,473,284.694 us |  45,544.4956 us |  40,374.0090 us |  2,461,672.220 us |  1.02 |    0.03 |  46000.0000 | 44000.0000 | 5000.0000 |  817572920 B |        1.96 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |           200 |      10000 |             1 |  5,675,256.875 us |  68,840.3599 us |  64,393.3154 us |  5,649,214.199 us |  1.00 |    0.00 |  39000.0000 | 38000.0000 | 4000.0000 |  705584912 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |      10000 |             1 |  5,672,162.872 us | 112,179.5288 us | 145,865.0742 us |  5,631,355.038 us |  1.00 |    0.03 |  49000.0000 | 25000.0000 | 1000.0000 |  945579024 B |        1.34 |
| AsyncDuplicateLockFromAutoCrud |           200 |      10000 |             1 |  5,281,978.600 us |  99,746.1564 us | 102,431.9589 us |  5,262,748.876 us |  0.93 |    0.03 |  60000.0000 | 32000.0000 | 4000.0000 | 1105590312 B |        1.57 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |           200 |      10000 |             5 | 14,550,111.222 us | 109,343.9720 us | 102,280.4192 us | 14,550,992.655 us |  1.00 |    0.00 | 100000.0000 | 36000.0000 | 4000.0000 | 1857600384 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |           200 |      10000 |             5 | 14,404,607.729 us | 157,404.6733 us | 139,535.1429 us | 14,406,175.422 us |  0.99 |    0.01 | 111000.0000 | 38000.0000 | 2000.0000 | 2097598672 B |        1.13 |
| AsyncDuplicateLockFromAutoCrud |           200 |      10000 |             5 | 14,413,920.281 us | 108,909.1081 us | 101,873.[6473](https://github.com/MarkCiliaVincenti/AsyncKeyedLockBenchmarks/actions/runs/3941257523/jobs/6743429454#step:4:6474) us | 14,408,098.268 us |  0.99 |    0.01 | 123000.0000 | 44000.0000 | 5000.0000 | 2257612712 B |        1.22 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |        100 |             0 |  1,193,779.741 us |  23,378.2787 us |  33,528.4287 us |  1,181,647.983 us |  1.00 |    0.00 |  10000.0000 | 10000.0000 | 1000.0000 |  208782184 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |        100 |             0 |  1,342,527.074 us |  26,274.7725 us |  43,899.2424 us |  1,337,933.798 us |  1.12 |    0.05 |  17000.0000 | 16000.0000 | 1000.0000 |  328781408 B |        1.57 |
| AsyncDuplicateLockFromAutoCrud |         10000 |        100 |             0 |  1,161,648.874 us |  20,657.6525 us |  18,312.4709 us |  1,157,166.135 us |  0.97 |    0.04 |  23000.0000 | 22000.0000 | 3000.0000 |  408782784 B |        1.96 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |        100 |             1 |  2,779,377.019 us |  54,612.6189 us |  51,084.6776 us |  2,786,048.230 us |  1.00 |    0.00 |  19000.0000 | 19000.0000 | 2000.0000 |  352795384 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |        100 |             1 |  2,842,961.114 us |  55,019.5647 us |  77,129.7456 us |  2,834,469.662 us |  1.03 |    0.03 |  26000.0000 | 14000.0000 | 2000.0000 |  472793992 B |        1.34 |
| AsyncDuplicateLockFromAutoCrud |         10000 |        100 |             1 |  2,561,215.067 us |  28,748.6090 us |  26,891.4667 us |  2,564,279.632 us |  0.92 |    0.02 |  31000.0000 | 17000.0000 | 3000.0000 |  552805064 B |        1.57 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |        100 |             5 |  7,241,014.629 us |  65,805.0420 us |  61,554.0772 us |  7,249,002.539 us |  1.00 |    0.00 |  50000.0000 | 18000.0000 | 2000.0000 |  928798728 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |        100 |             5 |  7,269,290.205 us |  90,233.5076 us |  84,404.4790 us |  7,236,094.419 us |  1.00 |    0.02 |  57000.0000 | 21000.0000 | 3000.0000 | 1048811072 B |        1.13 |
| AsyncDuplicateLockFromAutoCrud |         10000 |        100 |             5 |  7,381,969.023 us |  60,036.9236 us |  53,221.1690 us |  7,391,419.526 us |  1.02 |    0.01 |  63000.0000 | 24000.0000 | 4000.0000 | 1128811896 B |        1.22 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |      10000 |             0 |          1.242 us |       0.0354 us |       0.1017 us |          1.300 us |  1.00 |    0.00 |           - |          - |         - |        936 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |      10000 |             0 |          1.348 us |       0.0351 us |       0.0996 us |          1.301 us |  1.09 |    0.11 |           - |          - |         - |        936 B |        1.00 |
| AsyncDuplicateLockFromAutoCrud |         10000 |      10000 |             0 |          1.323 us |       0.0369 us |       0.1033 us |          1.300 us |  1.07 |    0.13 |           - |          - |         - |        936 B |        1.00 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |      10000 |             1 |          1.408 us |       0.0466 us |       0.1351 us |          1.400 us |  1.00 |    0.00 |           - |          - |         - |        936 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |      10000 |             1 |          1.323 us |       0.0429 us |       0.1250 us |          1.300 us |  0.95 |    0.13 |           - |          - |         - |        936 B |        1.00 |
| AsyncDuplicateLockFromAutoCrud |         10000 |      10000 |             1 |          1.676 us |       0.0680 us |       0.1973 us |          1.700 us |  1.20 |    0.19 |           - |          - |         - |        936 B |        1.00 |
|                                |               |            |               |                   |                 |                 |                   |       |         |             |            |           |              |             |
|                 AsyncKeyedLock |         10000 |      10000 |             5 |          1.526 us |       0.0381 us |       0.1082 us |          1.500 us |  1.00 |    0.00 |           - |          - |         - |        936 B |        1.00 |
|  AsyncKeyLockFromImageSharpWeb |         10000 |      10000 |             5 |          1.371 us |       0.0332 us |       0.0755 us |          1.400 us |  0.90 |    0.08 |           - |          - |         - |        936 B |        1.00 |
| AsyncDuplicateLockFromAutoCrud |         10000 |      10000 |             5 |          1.122 us |       0.0504 us |       0.1438 us |          1.100 us |  0.74 |    0.11 |           - |          - |         - |        936 B |        1.00 |`

**Comment by MarkCiliaVincenti** [comment]
> sweet! i'll wait for the results and review them ASAP! thank you!

Ready.

On a low number of locks and contention, AsyncDuplicateLock takes less time but allocates 92% more memory with 0 guid reversals (did some work here so that it simulates doing stuff), 55% more with 1 guid reversal and 21% more with 5 guid reversals.

Under heavy load though, AsyncDuplicateLock is slower and still allocates less memory (ranging between 22% and 96% more).

**Comment by JacobAtchley** [comment]
> 

thanks for the benchmarks once the build passes its tests i'll approve and merge the PR. thank you for your contribution!

**Comment by MarkCiliaVincenti** [comment]
> > 
> 
> thanks for the benchmarks once the build passes its tests i'll approve and merge the PR. thank you for your contribution!

Cool cool cool cool

... but what broke now?

**Comment by JacobAtchley** [comment]
> but what broke now?

we use `dotnet format` on our projects to cut out noise on the PRs

>Warning: /home/runner/work/auto-crud/auto-crud/Firebend.AutoCrud.Core/Threading/AsyncDuplicateLock.cs(10,50): warning IDE1006: Naming rule violation: Prefix '_' is not expected 

you can fix it with `dotnet format` at the root of the project

 think it is mad about this line

`private static readonly AsyncKeyedLocker _asyncKeyedLocker = new();`

i think it wants it to be `private static readonly AsyncKeyedLocker AsyncKeyedLocker = new();`

**Comment by MarkCiliaVincenti** [comment]
> > but what broke now?
> 
> we use `dotnet format` on our projects to cut out noise on the PRs
> 
> > Warning: /home/runner/work/auto-crud/auto-crud/Firebend.AutoCrud.Core/Threading/AsyncDuplicateLock.cs(10,50): warning IDE1006: Naming rule violation: Prefix '_' is not expected
> 
> you can fix it with `dotnet format` at the root of the project
> 
> think it is mad about this line
> 
> `private static readonly AsyncKeyedLocker _asyncKeyedLocker = new();`
> 
> i think it wants it to be `private static readonly AsyncKeyedLocker AsyncKeyedLocker = new();`

Check now please. Edited from my phone from bed :)

**Comment by MarkCiliaVincenti** [comment]
Sorry, I broke something typing from my phone. Hopefully it is fine now.

**Comment by MarkCiliaVincenti** [comment]
Last try for today otherwise I wait until I'm on a PC tomorrow or else I'll break my phone soon 😂

**Comment by larnth** [comment]
Well done :)

**Pull request merged**
